name: drinkable
description: A Flutter application which keeps track your water intake and remind you to drink water by sending notification.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  google_fonts: ^2.1.0
  provider: ^5.0.0
  firebase_core: ^1.0.0
  firebase_core_platform_interface: 4.5.1
  firebase_auth: ^1.0.0
  cloud_firestore: ^2.0.0
  google_sign_in: ^6.1.4
  location: ^4.0.0
  http: ^0.13.3
  flutter_local_notifications: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
